'''Given: A DNA string s
s
 of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s
'''

s = 'AGACTCGCGCACTCACGATGAATCCCAAGACAGCCTGGCGGAGTATGGTACTACGGCCGTCCTCACCAAGGCATTTCGGTCCGAGTAGCGGATTGTGTGCCAGCCCTGAGGGCGAGTTATGGGCTCATTCGGGAGACGTATGTACGAGCCTGATCGTTCGTCTGCATCGCTCTAATGTTTATCGACAGCCTTACCACTGTTTGAGTCGATGCAAGACCTGTTTCTTCAGCGCATTCACAGAGTGGCGCGAGACATACCACCAATACATAAGCGTAATTCTTACCGGCGTAGATCCCTAGGAGAGATCCAGCAAACTCGTTGTCATGGGTGACCGATACGCTCCTCAGTGGTCTCGACGGTTGTCTAGACGCGTCGTGCCGACAGTTGGCAATGCCAGTGGATCCGCATCCGAATTTCATGTGCTTTTAGAGCTTCGCTCATGCGTTCCACCGCCACGAGGCCAGCGAGGTGAGCCTTTTCCGGGAAGCCAACTGCACGGATCGCCCACTAGTGGATGAGCCACACTAAACATAGAATGAAACCCCGACCCCAACACGCCACCGTGTGTCGGGGATATTAGCCAACATTTGGTTTTGAGCGTTCCTCGGACCAGCTTCTCGATATACACGGAGCCTTCGGGATTCTGTCCCCTACCCTACCGCAGTCATATTCGGAGTCGGCTGGATCTCGATTCGTCTGGCAACCTGGGGTTTGTCATGCGGCAGGCCAGCTGCCTTGTCAAAGCCTATCGTCCCCAGGGGAACCAGGTAGAGGGTCGTGGTGTCGTAAGGAGACGCGTCGTGGCGACCACCTCAATCCGAGACGGCGACAAACATTTGCCGTTCCGTATAGGTACCTCCTAAGGTCGTCGAACTTCTAAGTCTCTGAATCTCCAGAACTCAATTCAGCGGATGGTAATGTCTCACAAGACTCGCTTGAGGCGGGCCCAT'

a = 'A'
c = 'C'
g = 'G'
t = 'T'
acount = 0
ccount = 0
gcount = 0
tcount = 0
for i in range(0, len(s)):
    if a == s[i]:
        acount += 1
    elif c == s[i]:
        ccount += 1
    elif g == s[i]:
        gcount += 1
    elif t == s[i]:
        tcount += 1

print(acount, ccount, gcount, tcount)
